from skills_db import skills
import random

question_bank={
    "python":[
        "What are Python’s key features?",
        "What are Python’s data types?",
        "What is the difference between list, tuple, and set?",
        "Explain Python’s memory management",
        "What are Python namespaces and scopes?",
        "What are Python decorators and how are they used?",
        "Explain Python’s *args and **kwargs.",
        "What is the difference between shallow copy and deep copy?",
        "What is the difference between @staticmethod, @classmethod, and instance methods?",
        "Explain Python’s inheritance types. (single, multiple, multilevel, hybrid)",
        "What are Python generators and how do they differ from iterators?",
        "What is the Global Interpreter Lock (GIL)?",
        "Explain Python’s memory optimization with __slots__.",
        "What is the difference between Python 2 and Python 3?",
        "How does Python handle exceptions?",
        "What is the difference between import and from import?",
        "Explain Python’s __init__.py file.",
        "What are virtual environments and why are they used?",
        "What is the difference between NumPy arrays and Python lists?",
        "Explain Python’s with statement and context managers."
    ],
    "sql":[
        "What is the difference between SQL and MySQL?",
        "Explain the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN.",
        "What is normalization? Explain its types.",
        "What are indexes in SQL and why are they used?",
        "What is the difference between clustered and non-clustered indexes?",
        "Explain the difference between WHERE and HAVING clauses.",
        "What is the difference between DELETE, TRUNCATE, and DROP?",
        "What are primary keys and foreign keys?",
        "Explain the difference between UNION and UNION ALL.",
        "What is a subquery? Give an example.",
        "What is the difference between correlated and non-correlated subqueries?",
        "Explain the difference between CHAR and VARCHAR data types.",
        "What is the difference between OLTP and OLAP systems?",
        "What are SQL constraints? Name a few.",
        "What is the difference between stored procedures and functions?",
        "Explain the difference between RANK(), DENSE_RANK(), and ROW_NUMBER().",
        "What is a view in SQL? How is it different from a table?",
        "What is ACID property in databases?",
        "Explain the difference between INNER JOIN and CROSS JOIN.",
        "What is the difference between EXISTS and IN operators?"
    ],
    "numpy": [
        "What is NumPy and why is it used?",
        "Explain the difference between ndarray and list.",
        "How do you create arrays in NumPy?",
        "What are broadcasting rules in NumPy?",
        "Explain vectorization in NumPy.",
        "How do you perform element-wise operations?",
        "What is the difference between reshape() and resize()?",
        "How do you handle missing values in NumPy?",
        "Explain the use of axis in NumPy functions.",
        "What is the difference between copy() and view()?",
        "How do you stack arrays vertically and horizontally?",
        "Explain the difference between np.zeros(), np.ones(), and np.empty().",
        "How do you generate random numbers in NumPy?",
        "What is the difference between np.sum() and np.mean()?",
        "How do you find unique elements in an array?",
        "Explain the difference between np.dot() and np.matmul().",
        "How do you perform sorting in NumPy?",
        "What is the difference between np.argmax() and np.argmin()?",
        "How do you save and load arrays?",
        "Explain memory efficiency in NumPy arrays."
    ],
    "pandas": [
        "What is Pandas and why is it used?",
        "Explain the difference between Series and DataFrame.",
        "How do you handle missing values in Pandas?",
        "What is the difference between loc[] and iloc[]?",
        "How do you merge, join, and concatenate DataFrames?",
        "Explain groupby() in Pandas.",
        "How do you perform pivot and pivot_table operations?",
        "What is the difference between apply(), map(), and applymap()?",
        "How do you handle categorical data in Pandas?",
        "Explain the difference between melt() and stack().",
        "How do you read and write CSV/Excel files?",
        "What is the difference between head(), tail(), and sample()?",
        "How do you perform indexing and slicing in Pandas?",
        "Explain the difference between drop() and dropna().",
        "How do you detect duplicates in a DataFrame?",
        "What is the difference between sort_values() and sort_index()?",
        "How do you perform time series analysis in Pandas?",
        "Explain the difference between astype() and convert_dtypes().",
        "How do you merge DataFrames with different keys?",
        "Explain performance optimization techniques in Pandas."
    ],
    "matplotlib": [
        "What is Matplotlib and why is it used?",
        "How do you create a simple line plot?",
        "Explain the difference between plt.plot() and plt.scatter().",
        "How do you add labels and titles to plots?",
        "How do you customize colors and styles?",
        "Explain the difference between figure and axes.",
        "How do you create subplots?",
        "What is the difference between plt.show() and plt.savefig()?",
        "How do you add legends to plots?",
        "Explain the difference between bar() and hist().",
        "How do you plot multiple lines on the same graph?",
        "How do you annotate plots?",
        "Explain the difference between tight_layout() and subplots_adjust().",
        "How do you change axis limits?",
        "How do you plot 3D graphs in Matplotlib?",
        "Explain the difference between interactive and non-interactive mode.",
        "How do you customize ticks and tick labels?",
        "How do you use stylesheets in Matplotlib?",
        "How do you plot images using imshow()?",
        "Explain performance considerations in Matplotlib."
    ],
    "seaborn": [
        "What is Seaborn and why is it used?",
        "How do you create a scatter plot in Seaborn?",
        "Explain the difference between sns.barplot() and sns.countplot().",
        "How do you create a heatmap?",
        "What is the difference between sns.boxplot() and sns.violinplot()?",
        "How do you customize Seaborn themes?",
        "Explain the difference between sns.catplot() and sns.relplot().",
        "How do you add regression lines using sns.lmplot()?",
        "How do you visualize distributions using sns.histplot()?",
        "Explain the difference between sns.pairplot() and sns.jointplot().",
        "How do you handle categorical vs numerical data in Seaborn?",
        "How do you customize color palettes?",
        "Explain the difference between sns.stripplot() and sns.swarmplot().",
        "How do you annotate heatmaps?",
        "How do you combine Seaborn with Matplotlib?",
        "Explain the difference between sns.FacetGrid() and sns.PairGrid().",
        "How do you plot time series data in Seaborn?",
        "How do you save Seaborn plots?",
        "How do you handle large datasets in Seaborn?",
        "Explain performance considerations in Seaborn."
    ],
    "plotly": [
        "What is Plotly and why is it used?",
        "How do you create interactive plots?",
        "Explain the difference between plotly.graph_objects and plotly.express.",
        "How do you create a line chart in Plotly?",
        "How do you create bar charts?",
        "Explain the difference between scatter plots and bubble charts.",
        "How do you create 3D plots in Plotly?",
        "How do you add tooltips and hover effects?",
        "How do you customize layouts and themes?",
        "Explain the difference between offline and online Plotly.",
        "How do you embed Plotly plots in Jupyter Notebook?",
        "How do you create maps using Plotly?",
        "Explain the difference between plotly.io and plotly.offline.",
        "How do you export Plotly plots?",
        "How do you add animations in Plotly?",
        "Explain the difference between update_layout() and update_traces().",
        "How do you handle large datasets in Plotly?",
        "How do you integrate Plotly with Dash?",
        "How do you customize legends in Plotly?",
        "Explain performance considerations in Plotly."
    ],
    "scikit-learn": [
        "What is scikit-learn and why is it used?",
        "Explain the difference between supervised and unsupervised learning.",
        "How do you split data into train and test sets?",
        "Explain the difference between fit(), transform(), and fit_transform().",
        "How do you perform feature scaling?",
        "Explain the difference between StandardScaler and MinMaxScaler.",
        "How do you perform cross-validation?",
        "Explain the difference between classification and regression.",
        "How do you evaluate model performance?",
        "Explain the difference between confusion matrix and classification report.",
        "How do you perform hyperparameter tuning?",
        "Explain the difference between GridSearchCV and RandomizedSearchCV.",
        "How do you handle imbalanced datasets?",
        "Explain the difference between PCA and LDA.",
        "How do you perform clustering in scikit-learn?",
        "Explain the difference between KMeans and DBSCAN.",
        "How do you save and load models?",
        "Explain the difference between pipeline and ColumnTransformer.",
        "How do you perform ensemble learning?",
        "Explain performance considerations in scikit-learn."
    ],
    "tensorflow": [
        "What is TensorFlow and why is it used?",
        "Explain the difference between TensorFlow 1.x and 2.x.",
        "How do you create tensors?",
        "Explain the difference between eager execution and graph execution.",
        "How do you build a neural network in TensorFlow?",
        "Explain the difference between Sequential and Functional API.",
        "How do you perform backpropagation in TensorFlow?",
        "Explain the difference between tf.Variable and tf.constant.",
        "How do you use tf.data for data pipelines?",
        "Explain the difference between tf.keras and pure Keras.",
        "How do you perform model training and evaluation?",
        "Explain the difference between common callbacks in TensorFlow, such as EarlyStopping, ModelCheckpoint, and ReduceLROnPlateau.",
        "How do you save and load models in TensorFlow?",
        "Explain the difference between TensorBoard and callbacks.",
        "How do you implement custom layers in TensorFlow?",
        "Explain the difference between tf.function and Python functions.",
        "How do you perform transfer learning in TensorFlow?",
        "Explain the difference between static and dynamic computation graphs.",
        "How do you deploy TensorFlow models?",
        "What are common performance optimization techniques in TensorFlow?"
    ],
    "pytorch": [
        "What is PyTorch and why is it used?",
        "Explain the difference between tensors in PyTorch and NumPy arrays.",
        "How do you create and manipulate tensors?",
        "Explain the difference between autograd and manual gradient computation.",
        "How do you build a neural network in PyTorch?",
        "Explain the difference between nn.Module and functional API.",
        "How do you perform backpropagation in PyTorch?",
        "Explain the difference between DataLoader and Dataset.",
        "How do you use optimizers in PyTorch?",
        "Explain the difference between torch.save and torch.load.",
        "How do you implement transfer learning in PyTorch?",
        "Explain the difference between CPU and GPU tensors.",
        "How do you visualize training with TensorBoard in PyTorch?",
        "Explain the difference between model.eval() and model.train().",
        "How do you handle large datasets in PyTorch?",
        "Explain the difference between torch.nn and torch.functional.",
        "How do you deploy PyTorch models?",
        "Explain the difference between dynamic and static computation graphs.",
        "How do you debug models in PyTorch?",
        "What are performance optimization techniques in PyTorch?"
    ],
    "docker": [
        "What is Docker and why is it used?",
        "Explain the difference between Docker containers and virtual machines.",
        "How do you create a Docker image?",
        "Explain the difference between docker run and docker start.",
        "How do you use Dockerfile?",
        "Explain the difference between docker build and docker pull.",
        "How do you manage Docker volumes?",
        "Explain the difference between docker-compose and Dockerfile.",
        "How do you expose ports in Docker?",
        "Explain the difference between ENTRYPOINT and CMD.",
        "How do you handle environment variables in Docker?",
        "Explain the difference between docker ps and docker images.",
        "How do you push and pull images from Docker Hub?",
        "Explain the difference between docker exec and docker attach.",
        "How do you optimize Docker images?",
        "Explain the difference between docker network and docker volume.",
        "How do you handle persistent storage in Docker?",
        "Explain the difference between docker logs and docker inspect.",
        "How do you secure Docker containers?",
        "What are best practices for Docker deployment?"
    ],
    "streamlit": [
        "What is Streamlit and why is it used?",
        "How do you create a simple Streamlit app?",
        "Explain the difference between st.write() and st.text().",
        "How do you add file upload functionality?",
        "Explain the difference between st.sidebar and main UI.",
        "How do you add charts in Streamlit?",
        "Explain the difference between st.line_chart and st.bar_chart.",
        "How do you handle user input in Streamlit?",
        "Explain the difference between st.selectbox and st.multiselect.",
        "How do you add interactive widgets?",
        "Explain the difference between st.dataframe and st.table.",
        "How do you cache functions in Streamlit?",
        "Explain the difference between st.session_state and global variables.",
        "How do you deploy Streamlit apps?",
        "Explain the difference between Streamlit Cloud and local deployment.",
        "How do you add images and media?",
        "Explain the difference between st.form and st.button.",
        "How do you handle authentication in Streamlit?",
        "How do you optimize performance in Streamlit apps?",
        "What are best practices for building recruiter-facing apps in Streamlit?"
    ],
    "c": [
        "What are the main features of C?",
        "Explain the difference between malloc() and calloc().",
        "What is the difference between array and pointer?",
        "Explain static vs dynamic memory allocation.",
        "What are storage classes in C?",
        "Explain the difference between struct and union.",
        "What is a segmentation fault?",
        "Explain recursion in C.",
        "What is the difference between pass by value and pass by reference?",
        "Explain macros in C.",
        "What is the difference between const and volatile?",
        "Explain inline functions in C.",
        "What are header files?",
        "Explain bitwise operators.",
        "What is the difference between stack and heap?",
        "Explain function pointers.",
        "What is the difference between exit() and return?",
        "Explain preprocessor directives.",
        "What is the difference between global and static variables?",
        "Explain performance optimization techniques in C."
    ],
    "c++": [
        "What are the main features of C++?",
        "Explain object-oriented programming concepts in C++.",
        "What is the difference between class and struct?",
        "Explain constructors and destructors.",
        "What is operator overloading?",
        "Explain function overloading vs overriding.",
        "What is the difference between virtual and pure virtual functions?",
        "Explain inheritance in C++.",
        "What is polymorphism?",
        "Explain templates in C++.",
        "What is the difference between shallow copy and deep copy?",
        "Explain smart pointers.",
        "What is the difference between new and malloc?",
        "Explain exception handling in C++.",
        "What is the difference between STL vector and list?",
        "Explain namespaces in C++.",
        "What is the difference between static and dynamic binding?",
        "Explain multiple inheritance.",
        "What is the difference between C++98, C++11, and C++17?",
        "Explain performance optimization techniques in C++."
    ],
    "java": [
        "What are Java’s main features?",
        "Explain JVM, JRE, and JDK.",
        "What is the difference between abstract class and interface?",
        "Explain inheritance in Java.",
        "What is polymorphism?",
        "Explain encapsulation.",
        "What is the difference between HashMap and Hashtable?",
        "Explain Java’s memory management.",
        "What is garbage collection?",
        "Explain checked vs unchecked exceptions.",
        "What is multithreading?",
        "Explain synchronized keyword.",
        "What is the difference between final, finally, and finalize?",
        "Explain Java Collections Framework.",
        "What is the difference between ArrayList and LinkedList?",
        "Explain Java’s access modifiers.",
        "What is the difference between == and equals()?",
        "Explain Java’s String pool.",
        "What is JDBC?",
        "Explain performance optimization techniques in Java."
    ],
    "html": [
        "What is HTML and why is it used?",
        "Explain semantic HTML.",
        "What is the difference between block and inline elements?",
        "Explain HTML forms.",
        "What are HTML attributes?",
        "Explain HTML5 new features.",
        "What is the difference between <div> and <span>?",
        "Explain HTML tables.",
        "What is the difference between id and class?",
        "Explain HTML multimedia tags.",
        "What is the difference between relative and absolute URLs?",
        "Explain HTML lists.",
        "What is the difference between inline and internal CSS?",
        "Explain HTML meta tags.",
        "What is the difference between <section>, <article>, and <aside>?",
        "Explain HTML canvas.",
        "What is the difference between <script> and <noscript>?",
        "Explain accessibility in HTML.",
        "What is the difference between HTML and XHTML?",
        "Explain performance optimization techniques in HTML."
    ],
    "css": [
        "What is CSS and why is it used?",
        "Explain inline, internal, and external CSS.",
        "What are CSS selectors?",
        "Explain the difference between relative, absolute, and fixed positioning.",
        "What is the difference between inline-block and block?",
        "Explain CSS specificity.",
        "What is the difference between em, rem, and px?",
        "Explain CSS flexbox.",
        "What is CSS grid?",
        "Explain media queries.",
        "What is the difference between relative and absolute units?",
        "Explain CSS pseudo-classes.",
        "What is the difference between inline styles and stylesheets?",
        "Explain CSS transitions.",
        "What is the difference between animations and transitions?",
        "Explain z-index in CSS.",
        "What is the difference between visibility and display?",
        "Explain CSS variables.",
        "What is the difference between min-width and max-width?",
        "Explain performance optimization techniques in CSS."
    ],
    "javascript": [
        "What are JavaScript’s key features?",
        "Explain var, let, and const.",
        "What is hoisting?",
        "Explain closures.",
        "What is the difference between == and ===?",
        "Explain event bubbling and capturing.",
        "What is the difference between synchronous and asynchronous code?",
        "Explain promises.",
        "What is async/await?",
        "Explain JavaScript’s prototype chain.",
        "What is the difference between null and undefined?",
        "Explain arrow functions.",
        "What is the difference between call, apply, and bind?",
        "Explain JavaScript’s event loop.",
        "What is JSON?",
        "Explain localStorage vs sessionStorage.",
        "What is the difference between GET and POST?",
        "Explain JavaScript modules.",
        "What is DOM manipulation?",
        "Explain performance optimization techniques in JavaScript."
    ],
    "aws": [
        "What is AWS and why is it used?",
        "Explain EC2 instances.",
        "What is S3?",
        "Explain IAM roles and policies.",
        "What is RDS?",
        "Explain Lambda functions.",
        "What is CloudFormation?",
        "Explain Elastic Load Balancer.",
        "What is Auto Scaling?",
        "Explain VPC.",
        "What is Route 53?",
        "Explain CloudWatch.",
        "What is DynamoDB?",
        "Explain difference between public and private subnets.",
        "What is EKS?",
        "Explain difference between ECS and EKS.",
        "What is AWS Glue?",
        "Explain AWS security best practices.",
        "What is AWS CloudTrail?",
        "Explain performance optimization techniques in AWS."
    ],
    "fastapi": [
        "What is FastAPI and why is it used?",
        "Explain the difference between FastAPI and Flask.",
        "What are path parameters?",
        "Explain query parameters in FastAPI.",
        "What is dependency injection?",
        "Explain request and response models.",
        "What is Pydantic?",
        "Explain FastAPI’s async support.",
        "What is middleware in FastAPI?",
        "Explain FastAPI routing.",
        "What is FastAPI’s automatic documentation?",
        "Explain FastAPI background tasks.",
        "What is FastAPI’s dependency overrides?",
        "Explain FastAPI’s security features.",
        "What is OAuth2 in FastAPI?",
        "Explain FastAPI’s WebSocket support.",
        "What is FastAPI’s performance advantage?",
        "Explain FastAPI deployment options.",
        "What is FastAPI’s testing support?",
        "Explain performance optimization techniques in FastAPI."
    ],
    "mlflow": [
        "What is MLflow and why is it used?",
        "Explain MLflow tracking.",
        "What is MLflow projects?",
        "Explain MLflow models.",
        "What is MLflow registry?",
        "Explain MLflow’s integration with scikit-learn.",
        "What is MLflow’s integration with TensorFlow?",
        "Explain MLflow’s integration with PyTorch.",
        "What is MLflow’s REST API?",
        "Explain MLflow’s UI.",
        "What is MLflow’s experiment tracking?",
        "Explain MLflow’s logging parameters.",
        "What is MLflow’s artifact storage?",
        "Explain MLflow’s deployment options.",
        "What is MLflow’s model packaging?",
        "Explain MLflow’s reproducibility features.",
        "What is MLflow’s integration with cloud platforms?",
        "Explain MLflow’s performance optimization.",
        "What is MLflow’s role in MLOps?",
        "Explain MLflow’s security best practices."
    ],
    "excel": [
        "What is Microsoft Excel and why is it used?",
        "Explain Excel formulas.",
        "What are Excel functions?",
        "Explain pivot tables.",
        "What is conditional formatting?",
        "Explain Excel charts.",
        "What are Excel macros?",
        "Explain Excel data validation.",
        "What is VLOOKUP?",
        "Explain HLOOKUP.",
        "What is INDEX-MATCH?",
        "Explain Excel’s text functions.",
        "What is Excel’s date functions?",
        "Explain Excel’s logical functions.",
        "What is Excel’s financial functions?",
        "Explain Excel’s statistical functions.",
        "What is Excel’s data analysis toolpak?",
        "Explain Excel’s power query.",
        "What is Excel’s power pivot?",
        "Explain performance optimization techniques in Excel."
    ],
        "powerbi": [
        "What is Power BI and why is it used?",
        "Explain Power BI Desktop vs Power BI Service.",
        "What are datasets in Power BI?",
        "Explain Power BI dashboards.",
        "What are reports in Power BI?",
        "Explain Power BI data sources.",
        "What is Power Query?",
        "Explain DAX in Power BI.",
        "What are measures in Power BI?",
        "Explain calculated columns.",
        "What is Power BI Gateway?",
        "Explain Power BI security best practices.",
        "What is row-level security?",
        "Explain Power BI mobile app.",
        "What is Power BI Embedded?",
        "Explain Power BI performance optimization.",
         "What is Power BI API?",
        "Explain Power BI visualization best practices.",
        "What is Power BI workspace?",
        "Explain performance optimization techniques in Power BI."
    ]
}

def extract_skills(text):
    text_lower=text.lower()
    return [s for s in skills if s in text_lower]

def generate_questions(skills, n=3):
    result={}
    for skill in skills:
        if skill in question_bank:
            result[skill]=random.sample(
                question_bank[skill],
                min(n, len(question_bank[skill]))
            )
    return result